version: 2.0

jobs:
  "python-2.7":
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: py27-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: py27-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            poetry run mkdir -p /tmp/results
            poetry run py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-2.7

  "python-3.7":
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: py37-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: py37-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            poetry run mypy --py2 --ignore-missing-imports --junit-xml=/tmp/results/mypy.xml popget
            poetry run py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-3.7

  "python-3.8":
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: py38-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            pip install poetry
            poetry install
      - save_cache:
          key: py38-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            poetry run mypy --py2 --ignore-missing-imports --junit-xml=/tmp/results/mypy.xml popget
            poetry run py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-3.8

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.7"
      - "python-3.8"
